version: '3.2'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: coolapp
      MYSQL_USER: ISA_interviewing
      MYSQL_PASSWORD: interviews
      MYSQL_DB: isai

  db:
    image: mysql/mysql-server:8.0.23
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: ISA_interviewing
      MYSQL_PASSWORD: interviews
      MYSQL_DB: isai
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro